version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - attach_workspace:
                at: ~/repo
            - run:
                name: Installing dependencies
                command: npm install
            - run:
                name: Running tests
                command: npm run test
            - run:
                name: Build the package
                command: npm run build
            - run:
                name: Testing
                command: cat $NPM_TOKEN && cat $NPM
            - run:
                name: Publish package
                command: |
                  npm set //registry.npmjs.org/:_authToken=$NPM_TOKEN
                  npm publish --access public
workflows:
    build-and-test:
      jobs:
        - build-and-test