version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run:
              name: Installing dependencies
              command: npm install
            - run:
              name: Running tests
              command: npm test
            - run:
              name: Build the package
              command: npm build
            - run:
              name: Authenticate with registry
              command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
            - run:
              name: Publish package
              command: npm publish
workflows:
    build-and-test:
      jobs:
        - build-and-test