version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - attach_workspace:
                at: ~/repo
            - run:
                name: Installing dependencies
                command: npm install
            - run:
                name: Running tests
                command: npm run test
  publish:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - attach_workspace:
                at: ~/repo
            - run:
                name: Build the package
                command: npm run build
            - run:
                name: Publish package
                command: |
                    npm set $NPM_AUTH
                    npm publish --access public
workflows:
  for tags:
    jobs:
      - test:
          filters:
            tags:
              only: /^v.*/
            branches:
              only: /^v.*/
      - publish:
          requires:
              - test
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
    build and publish:
      jobs:
        - test:
          filters:
            tags:
              only: /^v.*/
        - publish:
            requires:
                - test
            filters:
              tags:
                only: /^v.*/
              branches:
                ignore: /.*/