version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
<<<<<<< HEAD
            - attach_workspace:
                at: ~/repo
            - run:
                name: Installing dependencies
                command: npm install
            - run:
                name: Running tests
                command: npm run test
            - run:
                name: Build the package
                command: npm run build
            - run:
                name: Publish package
                command: |
                  npm set //registry.npmjs.org/:_authToken=$NPM_TOKEN
                  npm publish --access public
=======
            - run: npm install
            - run: npm test
            - run: npm build
            - run: npm publish
>>>>>>> Added build and publish step
workflows:
    build-and-test:
      jobs:
        - build-and-test