version: 2.1
orbs:
  node: circleci/node@2.0.2
# jobs:
#   test:
#     executor:
#       name: node/default
#     steps:
#       - checkout
#       - node/default:
#           steps:
#             - attach_workspace:
#                 at: ~/repo
#             - run:
#                 name: Installing dependencies
#                 command: npm install
#             - run:
#                 name: Running tests
#                 command: npm run test
#   publish:
#     executor:
#       name: node/default
#     steps:
#       - checkout
#       - node/default:
#           steps:
#             - attach_workspace:
#                 at: ~/repo
#             - run:
#                 name: Build the package
#                 command: npm run build
#             - run:
#                 name: Publish package
#                 command: |
#                     npm set //registry.npmjs.org/:_authToken=$NPM
#                     npm publish --access public
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - node/install-npm:
          filters:
            tags:
              only: /.*/
      # - publish:
      #     requires:
      #       - test
      #     filters:
      #       tags:
      #         only: /^v.*/
      #       branches:
      #         ignore: /.*/